
import Link from "next/link";
import "./css/plugins.bundle.css";
import "./css/style.bundle.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="ko">
            <head>
                
                {/* Favicon (중복되더라도 안전하게 처리) */}
                <link rel="shortcut icon" href="/images/logo/favicon.ico" />
                
                {/* Fonts */}
                <link href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" rel="stylesheet"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"/>
                
                {/* Stylesheets 
                <link href="/css/plugins.bundle.css" rel="stylesheet" type="text/css" />
                <link href="/css/style.bundle.css" rel="stylesheet" type="text/css" />
                */}
            </head>
            
            
            {children}
            
            
        </html>
    );
}


export const metadata = {
    title: "KEES 관리",
    description: "Generated by 포테이토",

    keywords: [
        "kees",
        "kees app",
        "kees앱",
        "키스앱",
        "쿠폰",
        "kees쿠폰",
        "사업자",
    ],
    /*
    viewport: {
        width: "device-width",
        initialScale: 1,
    },*/

    icons: {
        icon: "/images/logo/favicon.ico", // 이것만으로는 때때로 불완전할 수 있음
        shortcut: "/images/logo/favicon.ico",
        apple: "/images/logo/favicon.ico",
    },

    openGraph: {
        locale: "en_US",
        type: "website",
        url: "https://www.kees.com/kees",
        title: "kees",
        siteName: "kees",
    },
};



    